### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by phate1** [revolver-ocelot-saa/GhidraX64Dbg#1]
Hey, thanks for sharing just what im looking for although had issues installing it seemed to be due to the version number in extension.properties having to match the version of Ghidra otherwise it complains it's not compatible and won't install.

other than that worked a treat

**Comment by revolver-ocelot-saa** [comment]
@phate1 Thank you for opening an issue.  I was able to reproduce the issue against a clean box install of Ghidra.  

Also thank you for doing the leg work on the version number in extension.properties file, that seems to have fixed the issue. I updated the source and updated the pre-built release with the change.  Import worked successfully after the modifications, so I'll close this issue.
